const Data=[
    {
      activity:"run",
      description:"123",
      date:"1234",
      duration:"1hr"
    },
    {
      activity:"dive",
      description:"123",
      date:"1234",
      duration:"1hr"
    },
    {
      activity:"komkai",
      description:"123",
      date:"1234",
      duration:"1hr"
    },
    {
      activity:"run",
      description:"123",
      date:"1234",
      duration:"1hr"
    },
    {
      activity:"walk",
      description:"123",
      date:"1234",
      duration:"1hr"
    },
    {
      activity:"Deepak",
      description:"123",
      date:"1234",
      duration:"1hr"
    },

  ]
  export default Data;